config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders do
    member do
      put :return_car
      resources :fines, only: [:index, :show, :new, :create]
    end
  end
  resources :cars, only: [:index]

  root 'index#index'
  get 'index/index'

  post 'login' => 'login#sign_in'
  get 'login' => 'login#index'

  resources :registration, :only => [:index, :create]

  resources :adminka, :only => [:index, :create, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :status, class_name: 'CarStatus'
  belongs_to :condition, :class_name => 'CarCondition'

  def to_s
    self.brand
  end
end

app/models/car_condition.rb
class CarCondition < ApplicationRecord
  def to_s
    self.description
  end
end

app/models/car_status.rb
class CarStatus < ApplicationRecord
  def to_s
    self.description
  end
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :order, class_name: 'Order'

  def to_s
    "#{self.order}: #{self.reason} - #{self.cost}"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :car, class_name: 'Car'
  belongs_to :client, class_name: 'RentUser'
  belongs_to :admin, class_name: 'RentUser'
  belongs_to :status, class_name: 'OrderStatus'

  validates :car, :passport, :rent_time, :presence => true

  def to_s
    "#{self.client}: #{self.car}"
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord

  def to_s
    self.description
  end
end

app/models/rent_user.rb
class RentUser < ApplicationRecord
  belongs_to :role, class_name: 'Role'

  def admin?
    self.role == Role.find(1)
  end

  def to_s
    self.email
  end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    car_id = params['car']
    if car_id.nil? || car_id == ''
      @car = nil
      respond_to do |format|
        format.html {render :partial => "price", :object => "Select a Car to see price"}
      end
    else
      @car = Car.find(car_id)
      render :partial => "price", :object => @car
    end
  end
end

app/controllers/fines_controller.rb
class FinesController < ApplicationController
  before_filter :order_for_fines, only: [:index, :new, :show, :create]

  def index
    @fines = Fine.where(order: @order)
  end

  def show
    @fine = Fine.find(params[:id])
  end

  def new
    @fine = Fine.new
  end

  def create
    reason = params.require(:fine)[:reason]
    cost = params.require(:fine)[:cost]
    @fine = Fine.create(reason: reason, cost: cost, order: @order)
    if @fine.errors.empty?
      redirect_to fine_path(@fine)
    else
      render new_fine_path(@fine)
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def order_for_fines
    @order = Order.find(params[:id])
  end
end

app/helpers/adminka_helper.rb
module AdminkaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/my_order_helper.rb
module MyOrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  ORDER_STATUS = OrderStatus.all.collect{|os| [os.description, os.id]}
  AVAILABLE_CARS = Car.where(:status => CarStatus.find(1))#.collect { |p| [p.brand, p.id ] }.sort

  def available_cars
    Car.where(:status => CarStatus.find(1))
  end

  def car_conditions
    CarCondition.all
  end

  def order_statuses
    OrderStatus.order(:description)
  end
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/rent_car_helper.rb
module RentCarHelper

end

app/helpers/returned_car_helper.rb
module ReturnedCarHelper

end

app/helpers/view_order_helper.rb
module ViewOrderHelper
end

app/views/cars/_price.html.erb
<% if @car.nil? %>
    <%= content_tag :span, price %><br><br>
<% else %>
    <%= label :price, "Price per day: " %>
    <%= content_tag :span, @car.price %><br><br>
<% end %>

app/views/cars/index.html.erb
<h1>Cars#index</h1>
<p>Find me in app/views/cars/index.html.erb</p>

app/views/fines/create.html.erb
<h1>Fines#create</h1>
<p>Find me in app/views/fines/create.html.erb</p>

app/views/fines/destroy.html.erb
<h1>Fines#destroy</h1>
<p>Find me in app/views/fines/destroy.html.erb</p>

app/views/fines/edit.html.erb
<h1>Fines#edit</h1>
<p>Find me in app/views/fines/edit.html.erb</p>

app/views/fines/index.html.erb
<h1>Fines</h1>
<% if @fines.empty? %>
    <%= content_tag(:p, "There are no fines") %>
<% else %>
    <table class="orders">
      <caption>Fines for Order <%= @order.id %> </caption>
      <thead>
      <tr>
        <th>Fine id</th>
        <th>Order</th>
        <th>Reason</th>
        <th>Cost</th>
      </tr>
      </thead>
      <tbody>

      <% @fines.each do |fine| %>
          <tr data-fine-id="<%= fine.id%>">
            <td>
              <%= content_tag(:span, link_to(fine.id, fine_path(fine))) %>
            </td>
            <td>
              <%= content_tag(:span, fine.order) %>
            </td>
            <td>
              <%= content_tag(:span, fine.reason) + '$' %>
            </td>
            <td>
              <%= content_tag(:span, fine.cost) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/fines/new.html.erb
<%= form_for @fine do |f|%>
    <div class="form-style-6">
      <h1>Crete Fine</h1>
      <%= label_tag :order, 'Order: '%>
      <%= content_tag(:span, ("#{@order.client} - #{@order.car}"), :id => 'order') %><br><br>
      <%= f.label :reason, 'Reason:' %>
      <%= f.text_area :reason %><br>
      <%= f.label :cost, 'Cost:' %>
      <%= f.text_field :cost %><br>
      <%= f.submit 'Submmit' %>
    </div>
<% end %>

app/views/fines/show.html.erb
<%= link_to 'Orders', orders_path %>
<div class="form-style-6">
  <h1><%= "Fine: #{@fine.id}"%></h1>
  <div id="fine">
    <table>
      <tr>
        <td>
          <%= content_tag(:p, "Client:") %>
        </td>
        <td>
          <%= content_tag(:p, @fine.order.client) %>
        </td>
      </tr>
      <tr>
        <td>
          <%= content_tag(:p, "Car:") %>
        </td>
        <td>
          <%= content_tag(:p, @fine.order.car) %>
        </td>
      </tr>
      <tr>
        <td>
          <%= content_tag(:p, "Reason:") %>
        </td>
        <td>
          <%= content_tag(:p, @fine.reason) %>
        </td>
      </tr>
      <tr>
        <td>
          <%= content_tag(:p, "Cost:") %>
        </td>
        <td>
          <%= content_tag(:p, "#{@fine.cost}$") %>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/fines/update.html.erb
<h1>Fines#update</h1>
<p>Find me in app/views/fines/update.html.erb</p>