config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders do
    member do
      put :return_car
      resources :fines, only: [:index, :show, :new, :create]
    end
  end
  resources :cars, only: [:index]

  root 'index#index'
  get 'index/index'

  post 'login' => 'login#sign_in'
  get 'login' => 'login#index'

  resources :registration, :only => [:index, :create]

  resources :adminka, :only => [:index, :create, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :status, class_name: 'CarStatus'
  belongs_to :condition, :class_name => 'CarCondition'

  def to_s
    self.brand
  end
end

app/models/car_condition.rb
class CarCondition < ApplicationRecord
  def to_s
    self.description
  end
end

app/models/car_status.rb
class CarStatus < ApplicationRecord
  def to_s
    self.description
  end
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :order, class_name: 'Order'

  def to_s
    "#{self.order}: #{self.reason} - #{self.cost}"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :car, class_name: 'Car'
  belongs_to :client, class_name: 'RentUser'
  belongs_to :admin, class_name: 'RentUser'
  belongs_to :status, class_name: 'OrderStatus'

  validates :car, :passport, :rent_time, :presence => true

  def to_s
    "#{self.client}: #{self.car}"
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord

  def to_s
    self.description
  end
end

app/models/rent_user.rb
class RentUser < ApplicationRecord
  belongs_to :role, class_name: 'Role'

  def admin?
    self.role == Role.find(1)
  end

  def to_s
    self.email
  end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    car_id = params['car']
    if car_id.nil? || car_id == ''
      @car = nil
      respond_to do |format|
        format.html {render :partial => "price", :object => "Select a Car to see price"}
      end
    else
      @car = Car.find(car_id)
      render :partial => "price", :object => @car
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrdersHelper
  before_filter :get_user
  before_filter :find_order, only: [:show, :edit, :update]
  before_filter :check_if_admin, only: [:edit, :update]
  before_filter :active_orders, only: [:index, :return_car]


  def index
    @order_statuses = order_statuses
    @completed_orders = completed_orders
    orders_for_status(params[:status])
  end

  def return_car
    order_id = params['id']
    car_returned = OrderStatus.where(:description => 'Car returned').first
    respond_to do |format|
      update_successful = Order.find(order_id).update_attributes(:status => car_returned)
      if update_successful
          redirect_to orders_path
        format.json { render json: {} }
      else
        format.json { render json: update_successful.errors.to_json }
      end
    end
  end

  def show
  end

  def new
    @order = Order.new
    @available_cars = available_cars
  end

  def create
    client = current_user
    admin = get_admin
    status = OrderStatus.find(1)
    params = order_params.merge({:client => client, :admin => admin, :status => status})
    @order = Order.create(params)
    if @order.errors.empty?
      car = params[:car]
      car.update_attributes(:status => CarStatus.where(:description => 'Ordered').first)
      redirect_to order_path(@order)
    else
      @available_cars = available_cars
      render new_order_path
    end
  end

  def edit
    @order_statuses = OrderStatus.where.not(:description => 'All')#order_statuses
    @car_conditions = car_conditions
  end

  def update
    o_comment = params.require(:order)[:comment]
    new_status = OrderStatus.find(params.require(:order)[:status])
    new_params = {:comment => o_comment, :status => new_status}
    @order.update_attributes(new_params)
    if @order.errors.empty?
      car = @order.car
      car_status = get_new_car_status(new_status)
      car_condition = CarCondition.find(params[:condition])
      car.update_attributes(:status => car_status, :condition => car_condition)
      redirect_to order_path(@order)
    else
      render edit_order_path(@order)
    end

  end

  def destroy
  end

  private
  def order_params
    car_id = params.require(:order)[:car]
    car = Car.find(car_id)
    passport = params.require(:order)[:passport]
    rent_time = params.require(:order)[:rent_time]
    {:car => car, :passport => passport, :rent_time => rent_time}
  end

  def total_prices
    prices = []
    @orders.each { |order| prices << order.car.price * order.rent_time }
    @total_prices = prices.reduce(:+)
  end

  def find_order
    @order = Order.where(id: params[:id]).first
    render_404 unless @order
  end

  def get_new_car_status(order_status)
    if OrderStatus.where(:description => ['Completed', 'Declined']).include? order_status
      CarStatus.where(:description => 'Available For Rent').first
    elsif OrderStatus.where(:description => ['Approved', 'In Progress', 'Car returned']).include? order_status
      CarStatus.where(:description => 'In Rent').first
    elsif OrderStatus.where(:description => ['Received']).include? order_status
      CarStatus.where(:description => 'Ordered').first
    end
  end

  def active_orders
    @active_orders = OrderStatus.where(:description => ['Received', 'Approved', 'In Progress'])
  end

  def completed_orders
    OrderStatus.where(:description => ['Completed'])
  end

  def get_admin
    RentUser.where(:role => Role.find(1)).first
  end

  def current_user
    RentUser.where(:name => session[:name]).first
  end

  def orders_for_status(status)
    if status.nil?
      @orders = Order.all
      total_prices
    elsif OrderStatus.find(status).description == 'All'
      @orders = Order.all
      total_prices
      render :partial => "orders", :object => @orders
    else
      @orders = Order.where(:status => status)
      total_prices
      render :partial => "orders", :object => @orders
    end
  end
end

app/helpers/adminka_helper.rb
module AdminkaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/my_order_helper.rb
module MyOrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  ORDER_STATUS = OrderStatus.all.collect{|os| [os.description, os.id]}
  AVAILABLE_CARS = Car.where(:status => CarStatus.find(1))#.collect { |p| [p.brand, p.id ] }.sort

  def available_cars
    Car.where(:status => CarStatus.find(1))
  end

  def car_conditions
    CarCondition.all
  end

  def order_statuses
    OrderStatus.order(:description)
  end
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/rent_car_helper.rb
module RentCarHelper

end

app/helpers/returned_car_helper.rb
module ReturnedCarHelper

end

app/helpers/view_order_helper.rb
module ViewOrderHelper
end

app/views/orders/_admin_edit_order.html.erb
<%= form_for@order do |f| %>
    <div class="form-style-6">
      <%= f.label :car, 'Chosen car: '%>
      <%= f.text_field :car, :disabled => true%><br>
      <%= f.label :client, 'Client: '%>
      <%= f.text_field :client, :disabled => true %><br>
      <%= f.label :rent_time, 'Rent time: '%>
      <%= f.text_field :rent_time, :disabled => true %><br>
      <%= f.label :admin, 'Admin: '%>
      <%= f.text_field :admin, :disabled => true %><br>
      <%= f.label :status, 'Select Order Status: '%>
      <%= f.select :status, options_from_collection_for_select(@order_statuses, 'id', 'description')%><br>
      <%= label_tag :condition, 'Select Car Condition: '%>
      <%= select_tag :condition, options_from_collection_for_select(@car_conditions, 'id', 'description')%><br>
      <%= f.label :comment, 'Comment: '%>
      <%= f.text_area :comment %><br>
      <%= f.submit 'Update Order' %>
    </div>
<% end %>

app/views/orders/_orders.html.erb
<%= content_tag(:div, '', :id => "test_div" ) %>
<% if @orders.empty? %>
    <%= content_tag(:p, "There are no such orders") %>
<% else %>
    <table class="orders">
      <caption>Orders</caption>
      <thead>
      <tr>
        <th>Client</th>
        <th>Car</th>
        <th>Rent Time</th>
        <th>Cost</th>
        <th>Status</th>
        <th>Admin</th>
        <th>Comment</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>

      <% @orders.each do |order| %>
          <tr data-order-id="<%= order.id%>">
            <td>
              <%= content_tag(:span, order.client) %>
            </td>
            <td>
              <%= content_tag(:span, link_to(order.car, order_path(order))) %>
            </td>
            <td>
              <%= content_tag(:span, order.rent_time) %>
            </td>
            <td>
              <%= content_tag(:span, order.rent_time * order.car.price) + '$' %>
            </td>
            <td>
              <%= content_tag(:span, order.status) %>
            </td>
            <td>
              <%= content_tag(:span, order.admin) %>
            </td>
            <td>
              <%= content_tag(:span, order.comment)%>
            </td>
              <td>
                <% if @user.admin?%>
                    <% unless @completed_orders.include? order.status %>
                        <%= content_tag(:span, link_to('Change order', edit_order_path(order))) %>
                        <%= content_tag(:span, link_to('Create fine', new_fine_path(order))) %>
                    <% end %>
                <% else %>
                    <% if @active_orders.include? order.status %>
                        <%= content_tag(:div, button_to("Return Car", return_car_order_path(order.id), {:class => 'return_car', :remote => true, :method => :put})) %>
                    <% end %>
                <% end %>
                <% unless Fine.where(order: order).empty? %>
                  <%= content_tag(:span, link_to('Fines', fines_path(order))) %>
                <% end %>
              </td>
          </tr>
      <% end %>

      </tbody>
      <tfoot>
      <tr>
        <th colspan="3">Grand Total</th>
        <th><%= "#{@total_prices}$" %></th>
      </tr>
      </tfoot>
    </table>
<% end %>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1><% @order.car %></h1>

<% if @user.admin? %>
    <%= render partial: 'orders/admin_edit_order'%>
<% end %>

app/views/orders/index.html.erb
<script type="text/javascript">
  $(function () {
    $("#order_selection").on("change", function () {
      status = $(this).val();
      $.ajax({
        url: "/orders",
        type: "GET",
        data: {"status" : status},
        dataType: "html",
        success: function(data) {
          jQuery("#orders").html(data);
        }
      })
    });
    $(".return_car").on("click", function () {
      var current_item_tr = $(this).parents("tr")[0];
      var order_id = $(current_item_tr).attr("data-order-id");
      var status = $("#order_selection").val();
      if (confirm("Are you sure?")){
        $.ajax({
          url: "orders/" + order_id + "/return_car",
          type: 'PUT',
          contentType: 'application/json',
          dataType: 'json',
          data: JSON.stringify({"order": order_id, "status": status}),
          success: function(data, status, jq) {
            jQuery("#orders").html(data);
          },
          error: function (jq, status, err){
            document.getElementById("test_div").innerHTML = "err: " + err + "\nstatus: " + status + "\njq: " + jq
          }
        })
      }
    })
  })

</script>


  <%= content_tag(:div, link_to('Rent new car', new_order_path), :class => 'new_order') %><br>
  <%= select_tag :order_selection, options_from_collection_for_select(@order_statuses, 'id', 'description') %><br>
<form id="form">
  <%= content_tag(:div, (render :partial => 'orders', :object => @orders), :id => 'orders') %>
</form>

app/views/orders/new.html.erb
<script type="text/javascript">
    $(function () {
      $("#order_car").on('change', function () {
        car = $(this).val();
        $.ajax({
          url: '/cars',
          type: 'GET',
          data: {"car" : car},
          dataType: "html",
          success: function(data) {
            jQuery("#car_price").html(data);
          },
          error: function (jq, status, err) {
            alert("error on car select: " + err);
          }
        })
      })
    })
</script>

<%= form_for @order do |f|%>
    <div class="form-style-6">
      <h1>Rent Car</h1>
      <%= f.label :car, 'Choose a car: '%>
      <%= f.select :car, options_from_collection_for_select(@available_cars, "id", "brand"), include_blank: true %><br>
      <%= content_tag(:span, (render :partial => 'cars/price', :object => @car), :id => 'car_price') %>
      <%= f.label :passport, 'Your passport: '%>
      <%= f.text_field :passport%><br>
      <%= f.label :rent_time, 'Rent Time: '%>
      <%= f.text_field :rent_time%><br>
      <%= f.submit 'Submmit' %>
    </div>
<% end %>

app/views/orders/show.html.erb
<%= link_to 'Orders', orders_path %>
    <div class="form-style-6">
      <h1><%= @order.car%></h1>
      <table class="order_details">
        <tbody>
        <tr>
          <td>
            <%= content_tag(:span, "Client:") %>
          </td>
          <td>
            <%= content_tag(:span, @order.client) %>
          </td>
        </tr>
        <tr>
          <td>
            <%= content_tag(:span, "Rent Time:") %>
          </td>
          <td>
            <%= content_tag(:span, @order.rent_time) %>
          </td>
        </tr>
        <tr>
          <td>
            <%= content_tag(:span, "Car Price:") %>
          </td>
          <td>
            <%= content_tag(:span, @order.car.price) %>
          </td>
        </tr>
        <tr>
          <td>
            <%= content_tag(:span, "Admin:") %>
          </td>
          <td>
            <%= content_tag(:span, @order.admin) %>
          </td>
        </tr>
        <tr>
          <td>
            <%= content_tag(:span, "Car Status:") %>
          </td>
          <td>
            <%= content_tag(:span, @order.car.status) %>
          </td>
        </tr>
        <tr>
          <td>
            <%= content_tag(:span, "Car Condition:") %>
          </td>
          <td>
            <%= content_tag(:span, @order.car.condition) %>
          </td>
        </tr>
        <tr>
          <td>
            <%= content_tag(:span, "Total Cost:") %>
          </td>
          <td>
            <%= content_tag(:span, @order.car.price * @order.rent_time) %>
          </td>
        </tr>
        <tr>
          <td>
            <%= content_tag(:span, "Comment:") %>
          </td>
          <td>
            <%= content_tag(:span, @order.comment) %>
          </td>
        </tr>

        </tbody>
      </table>
    </div>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>